language: ruby
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
rvm:
- 2.5.3
before_install:
- yes | gem update --system --force
- gem install bundler
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn install
- RAILS_ENV=test bundle exec rails webpacker:compile
before_script:
- bundle exec rake db:create db:test:prepare
deploy:
  provider: heroku
  api_key:
<<<<<<< HEAD
    secure: cl8mFQJNiQ7lwcGSCbRB/PfCH0H/gK5dp+7ngGFZdUrJbAhSZdz/vZMm7dQkakZ55RgLsACjxakwx//0FICckit0GdijJpg/yqggBEUky7MeCaWyY27oYcG8aHPlULCbmrzYS5h6cMGxlnbmcmQu8cptrHgibfSmTzg/Z8iBDow3oYl2fKl4GxGt9Bc7C4I/AGTRlfF/JOfT4RGCiakEp3pak0iyH4zkTfm5w8M94SFbmKfGl0msVIS/vDNlVHe2Mo5h/hMNok6HUInf0X8hSaYXSaHLGf6hWHIKFn2wms3V9wWybbteEkZmClscUbMJWxCIQbX3ihGVWuw2zgE260GTbMYBB6tv5/UppfdXXyFaGa6IyQLbxYuRpHVH3pv5K3wRvDRK37vSeLVOQ7D/AE7u7m8y45m/IRKb8p8RpljZ5Y4wH0XvLF7YdYXuP0HL9YNT9tl6LgioEmqLXy6LEKVI851Jr1fbAOwFoC3mU/I2yfhNCZLxbsI8owdhA429rmoEq81ed6I5RIWx0Ysrgm2r1EoVd8W7CBDNvMXV04arLO3az6GPWZ/MWbGla0o4oIGoyyMvTWXn109AgOfM7XztIxCpApJsy6L5XFF9opl2Ba0w1mRnhxb7bWSqQUwdkacOoWQyHdF3m49L5LyoMZ5NR8aCY4d1dv/srJPcUyE=
  run: 'rake db:migrate'
=======
    secure: "gBA3/swvXyXUwl0aSkKXNwgnYDybRiwzp4uKd4sQ6n+0/jdJvV6MePan7lpfAF1k7SBQ0A/zjcx8NZx0PzDqeo8a/u1xt+lpcWvte6P/+IhAuSJQ6Vk6VEYchw1hp/CpPE64cTTYWLPVy9j5sETuiZXHEZReXW5JBG9MYZcySOqUpn5orDky6wQS69FqCWBftCpvAvkh+1pAGSPK1hEuy4/XCu7BVCctXfFSz0p/B2e7J0SYqmsc+5ylC9SO4H87mVF7A2FTPMQKomKOR6G3h5xCtFVPSfSD2+gsIvN/zPIAoeWf8VTXQvXrLbf7Ba7Mt90WiC1MnmVGnNtGu7ZPs3YBOduzcxVDLiT9LN66B6O2uyM4QU35zPoi2wd76L7xN1xt92cD9tqBhYCatPkBqw97nwaGTqhWIiFOl8XG+IZq8CEsSdnHneoGbnY7G6sf8NEfySbTINPrxt6qaNcQc8xEsv0OB0q8lNeFaE/Sd/+CghBmAm91ZsFSz8LOij1SDFEI840aeIJoPqDqTskSrc73HAyAwq79kr5ArZh1OcKJhg6UgIBI07J9j5riasuo0SC3Z8AHf5czHRPRMyqNNkXa02xbsknSsgxD5skR0uMbG47OYsBpb/+8aJkUAwcFR4+DY4LiMVVlojexX3PpMq/xDg1SmI+qXHmFJZRGzQM="
  run:
  - rake db:migrate
  - rake db:seed
>>>>>>> 1a399a0... Adjust .travis.yml
