language: ruby
cache: bundler
rvm:
  - 2.5.3
node_js: '10.15.3'
before_install:
  - yes | gem update --system --force
  - gem install bundler
install:
  - bundle install
  - bundle exec rails webpacker:install
